### ISSUE TITLE
头像可在前端直接使用B站api获取

### ISSUE THREAD

**Issue by Mrs4s** [3Shain/BiliChat#1]
首先
`GET https://api.bilibili.com/x/space/app/index?mid={USERID}` 请求时注意去掉Referer
然后解析json在`data->info->face`就能拿到头像url 
似乎没发现什么限制

**Comment by 3Shain** [comment]
浏览器cors限制，直接使用此地址会导致403forbidden。用浏览器直接打开没问题是因为没有origin头，但在网页中无论是xhr还是直接设置img.src都无法解决跨域问题。

**Comment by 3Shain** [comment]
浏览器cors限制，直接使用此地址会导致403forbidden。用浏览器直接打开没问题是因为没有origin头，但在网页中无论是xhr还是直接设置img.src都无法解决跨域问题。

**Comment by HarukaFuture** [comment]
> 浏览器cors限制，直接使用此地址会导致403forbidden。用浏览器直接打开没问题是因为没有origin头，但在网页中无论是xhr还是直接设置img.src都无法解决跨域问题。

https://images.weserv.nl/ 可以尝试一下(可选选择

**Comment by 3Shain** [comment]
> > 浏览器cors限制，直接使用此地址会导致403forbidden。用浏览器直接打开没问题是因为没有origin头，但在网页中无论是xhr还是直接设置img.src都无法解决跨域问题。
> 
> https://images.weserv.nl/ 可以尝试一下(可选选择

考虑添加此选项

**Comment by 3Shain** [comment]
> > > 浏览器cors限制，直接使用此地址会导致403forbidden。用浏览器直接打开没问题是因为没有origin头，但在网页中无论是xhr还是直接设置img.src都无法解决跨域问题。
> > 
> > 
> > https://images.weserv.nl/ 可以尝试一下(可选选择
> 
> 考虑添加此选项

除了图片代理，对b站api的请求也需要转发。如果找到了一个比较稳定的代理服务，可以统一做一个完全依赖于第三方服务的选项。这有可能带来高延时和高频率弹幕下稳定性的问题。

**Comment by imlonghao** [comment]
关于这个「稳定的代理服务」，想到了 Cloudflare Worker
`/api/avatar/` 和 `/api/stat/` 路径的都能用他做出来
运行在 Cloudflare 的边缘节点上，稳定性应该可以的，然后可以加缓存功能减少对B的请求

（就是价格每百万次请求0.5刀用的人多了会不会破产）
