### ISSUE TITLE
换个图标

### ISSUE THREAD

**Issue by 3Shain** [3Shain/BiliChat#10]
不再直接使用bilibili的icon，避免法律问题

**Comment by Afanyiyu** [comment]
[BiliChat.zip](https://github.com/3Shain/BiliChat/files/3142243/BiliChat.zip)

![Screenshot (8)](https://user-images.githubusercontent.com/20179549/57142985-6aa09c00-6df0-11e9-9cd3-7dd35078df37.png)

在？有需要改的话我再改
如果Staff表能加上我的话我能吹十年（x）

**Comment by Afanyiyu** [comment]
好的我承认最后一个是我画的，嘴画小了……
我改

**Comment by Afanyiyu** [comment]
[BiliChat.zip](https://github.com/3Shain/BiliChat/files/3142280/BiliChat.zip)

好的它修改过了
它叫做BiliChat_x_画板 1 副本 8.svg

**Comment by 3Shain** [comment]
那就决定是最后一个了！
能顺便弄一套ico文件吗，空白边框可以缩一点甚至去掉也可以

**Comment by Afanyiyu** [comment]
妈呀，得亏开了Github的Watch，秒速收到回复
然而Github这龟速，方滨兴出来挨打

然后……不使用iconfont而使用灵魂画手画的图标，不愧是大佬ㄟ(≧◇≦)ㄏ
好的我这就去弄

**Comment by Afanyiyu** [comment]
另外i18n我也在做了
能不能在开学之前做到PR的状态我就不知道了……

**Comment by Afanyiyu** [comment]
[Out.zip](https://github.com/3Shain/BiliChat/files/3142477/Out.zip)

看吧，我不光做了Black和Blue两个颜色，还贴心的做了OSX图标
所以Staff考虑一下（x）

PS：以这一版为准，上面的SVG有bug，有一部分没有透明

**Comment by Afanyiyu** [comment]
看了新的“弹幕堆叠”了，话说这样不就显示不出来AWSL大军的气势了吗……
……x

**Comment by simon300000** [comment]
manifest.json
apple-touch-icon
mask-icon
搞快点（滑稽

**Comment by simon300000** [comment]
> [Out.zip](https://github.com/3Shain/BiliChat/files/3142477/Out.zip)
> 
> 看吧，我不光做了Black和Blue两个颜色，还贴心的做了OSX图标
> 所以Staff考虑一下（x）
> 
> PS：以这一版为准，上面的SVG有bug，有一部分没有透明

@Afanyiyu 
那个蓝色版本好像有红色边框漏出来啦

**Comment by Afanyiyu** [comment]
又是收到了邮件的秒回……
……妈呀楼上四点不睡，夜猫子吧（虽说我也是）（deco出新单品了啊啊啊
……额那啥，我明天就开学了反正:-/，，等有时间吧，，那个logo你们先用着谢谢，i18n我有时间做

**Comment by simon300000** [comment]
> 又是收到了邮件的秒回……
> ……妈呀楼上四点不睡，夜猫子吧（虽说我也是）（deco出新单品了啊啊啊
> ……额那啥，我明天就开学了反正:-/，，等有时间吧，，那个logo你们先用着谢谢，i18n我有时间做

我想睡，睡不着。。。
还有就是蓝色版本，红色框框漏出来啦→_→！
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12656264/57162325-7c9a3300-6e20-11e9-96b3-1099a1c867f0.png">

**Comment by Afanyiyu** [comment]
活   捉   夜   猫   子
等着，我去拿（偷）过来电脑

**Comment by Afanyiyu** [comment]
预计四点半修复
（妈呀明天上午报到，我这是找死）

**Comment by simon300000** [comment]
那你还不睡觉，我有AI我可以尝试帮你修复了→_→
你先睡觉去吧。。。。

**Comment by Afanyiyu** [comment]
我来吧，毕竟ico也要一起修复

**Comment by simon300000** [comment]
好吧→_→

**Comment by Afanyiyu** [comment]
[Out_New.zip](https://github.com/3Shain/BiliChat/files/3143412/Out_New.zip)

毕竟我手也不慢啊
这个应该没问题了

**Comment by Afanyiyu** [comment]
代码也检查过了，应该没有问题
睡去了

**Comment by Afanyiyu** [comment]
话虽这么说，svg的代码覆盖率估计连50%都不到
有时间我clean一下
睡了

**Comment by Afanyiyu** [comment]
rgb麻烦自己吸一下啦~我记不清了好像是0，260，194（欸不对，记不清了）

**Comment by simon300000** [comment]
@3Shain 
ico文件好像只是IE要用
`<!--[if IE]><link rel="icon" href="/favicon.ico"><![endif]-->`

现在大多数浏览器似乎都支持这种方式用png
```html
<link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png">
```

用favicons做了个大礼包，送给你（许多是没用的2333
[Black.zip](https://github.com/3Shain/BiliChat/files/3143447/Black.zip)
[Blue.zip](https://github.com/3Shain/BiliChat/files/3143448/Blue.zip)

**Comment by 3Shain** [comment]
草你们居然在issue版聊起来了

**Comment by simon300000** [comment]
惊了，issue不就是拿来聊天的吗？

**Comment by Afanyiyu** [comment]
惊了，issue不就是拿来聊天的吗？（队形
还有这个图标可以叫做
一 般 发 情 小 电 视
睡了

**Comment by 3Shain** [comment]
暂时先采用这些啦
