### ISSUE TITLE
chat-renderer的一些奇怪症状

### ISSUE THREAD

**Issue by 3Shain** [3Shain/BiliChat#12]
评论有时会两条一起出来？

**Comment by imlonghao** [comment]
我觉得这个应该不算是奇怪的症状吧？或者我没理解到你的意思？

直播的弹幕在弹幕多的时候就是在同一个包里面给你塞多条弹幕的，所以解出来可能看上去就变成了两条或多条一起出来了。

**Comment by 3Shain** [comment]
> 我觉得这个应该不算是奇怪的症状吧？或者我没理解到你的意思？
> 
> 直播的弹幕在弹幕多的时候就是在同一个包里面给你塞多条弹幕的，所以解出来可能看上去就变成了两条或多条一起出来了。

事实上一个包塞了10+弹幕，我有故意拆分开，虽然我本地测试也是一条一条出来的，但看很多直播都是两条一起出来

**Comment by simon300000** [comment]
刚刚在看Aqua直播发现弹幕一会快一会慢，想到了一个解决办法

首先定义一个cache时间
收到弹幕就存到一个Array里，然后按照 Array.length/cache 的间隔显示弹幕
这样可以动态调整弹幕速度，并且起到一个按照cache时间的平均作用

但是缺点很明显，会增加延迟。

**Comment by 3Shain** [comment]
> 刚刚在看Aqua直播发现弹幕一会快一会慢，想到了一个解决办法
> 
> 首先定义一个cache时间
> 收到弹幕就存到一个Array里，然后按照 Array.length/cache 的间隔显示弹幕
> 这样可以动态调整弹幕速度，并且起到一个按照cache时间的平均作用
> 
> 但是缺点很明显，会增加延迟。
> 
> ps
> 应该可以通过某种技巧减少延迟的同时平均速度→_→
> 
> pss
> 然而这个方法似乎会导致你改好多代码
> （我不会RxJS

不知道你有没有仔细看过目前的renderer源码，但原理跟你说的基本一致。
目前是requestAnimationFrame入手的，间隔是(1秒/最大帧率)的整数倍

**Comment by simon300000** [comment]
> > 刚刚在看Aqua直播发现弹幕一会快一会慢，想到了一个解决办法
> > 首先定义一个cache时间
> > 收到弹幕就存到一个Array里，然后按照 Array.length/cache 的间隔显示弹幕
> > 这样可以动态调整弹幕速度，并且起到一个按照cache时间的平均作用
> > 但是缺点很明显，会增加延迟。
> > ps
> > 应该可以通过某种技巧减少延迟的同时平均速度→_→
> > pss
> > 然而这个方法似乎会导致你改好多代码
> > （我不会RxJS
> 
> 不知道你有没有仔细看过目前的renderer源码，但原理跟你说的基本一致。
> 目前是requestAnimationFrame入手的，间隔是(1秒/最大帧率)的整数倍

对不起，我其实刚刚才看到。我今天下午发现似乎多了个重复弹幕计数的功能，就过来翻了一下 commit 看到了 `this.waitForRendering` 那块地方。

Angular和Typescript看得我头有点大，代码读的比较慢。。。

**Comment by simon300000** [comment]
刚刚看Mea直播的时候卡的不得了，我怎么感觉单纯就是弹幕过多了卡了。。。
赶紧弃用Angular改用appendChild（滑稽

**Comment by 3Shain** [comment]
gkd-renderer解决了这个问题
