### ISSUE TITLE
【help/求助】请问我自己使用的话如何才能将弹幕中一些关键字筛选出来

### ISSUE THREAD

**Issue by Dreammer12138** [3Shain/BiliChat#13]
我JS苦手请不要介意。
在一般使用时有时候弹幕滚动速度太快无法准确获取观众的信息，因此我想将一些带有关键词的弹幕筛选出来，我明白需要添加一层条件判断，但是说实话我没有搞懂bilichat如何读取并输出弹幕信息的，请大神指点一下，谢谢

**Comment by 3Shain** [comment]
看下message-processor.service.ts

**Comment by Dreammer12138** [comment]
直接在wordFilter数组里面添加关键字好像不行啊
`this.wordFilter = [
            'kimo', '风暴',
            '弹幕姬', '弹幕机',
            '别刷', '不要刷',
            '小鬼', 'biss',
            '嘴臭', '骂我',
            '梗',
            '傻逼', '弱智', '脑残', '屏蔽', 'cnm',
            '警察', '加群', '群号', 'QQ群', '出警',
            '人工智能', '老婆', 'test'
        ];`

**Comment by 3Shain** [comment]
> 直接在wordFilter数组里面添加关键字好像不行啊
> `this.wordFilter = [ 'kimo', '风暴', '弹幕姬', '弹幕机', '别刷', '不要刷', '小鬼', 'biss', '嘴臭', '骂我', '梗', '傻逼', '弱智', '脑残', '屏蔽', 'cnm', '警察', '加群', '群号', 'QQ群', '出警', '人工智能', '老婆', 'test' ];`

这是筛除列表，包含关键字的会直接滤掉

**Comment by Dreammer12138** [comment]
直接在server.js文件中更改可以吗？
还是说得在源文件中更改以后重新打包？

**Comment by Dreammer12138** [comment]
> > 直接在wordFilter数组里面添加关键字好像不行啊
> > `this.wordFilter = [ 'kimo', '风暴', '弹幕姬', '弹幕机', '别刷', '不要刷', '小鬼', 'biss', '嘴臭', '骂我', '梗', '傻逼', '弱智', '脑残', '屏蔽', 'cnm', '警察', '加群', '群号', 'QQ群', '出警', '人工智能', '老婆', 'test' ];`
> 
> 这是筛除列表，包含关键字的会直接滤掉

直接在server.js文件中更改可以吗？
还是说得在源文件中更改以后重新打包？

**Comment by 3Shain** [comment]
> > > 直接在wordFilter数组里面添加关键字好像不行啊
> > > `this.wordFilter = [ 'kimo', '风暴', '弹幕姬', '弹幕机', '别刷', '不要刷', '小鬼', 'biss', '嘴臭', '骂我', '梗', '傻逼', '弱智', '脑残', '屏蔽', 'cnm', '警察', '加群', '群号', 'QQ群', '出警', '人工智能', '老婆', 'test' ];`
> > 
> > 
> > 这是筛除列表，包含关键字的会直接滤掉
> 
> 直接在server.js文件中更改可以吗？
> 还是说得在源文件中更改以后重新打包？

理论上可以直接改，但建议重新打包。

**Comment by Dreammer12138** [comment]
重新打包直接按源文件中的webpack.server.config.js打包就可以吗


> > > > 直接在wordFilter数组里面添加关键字好像不行啊
> > > > `this.wordFilter = [ 'kimo', '风暴', '弹幕姬', '弹幕机', '别刷', '不要刷', '小鬼', 'biss', '嘴臭', '骂我', '梗', '傻逼', '弱智', '脑残', '屏蔽', 'cnm', '警察', '加群', '群号', 'QQ群', '出警', '人工智能', '老婆', 'test' ];`
> > > 
> > > 
> > > 这是筛除列表，包含关键字的会直接滤掉
> > 
> > 
> > 直接在server.js文件中更改可以吗？
> > 还是说得在源文件中更改以后重新打包？
> 
> 理论上可以直接改，但建议重新打包。

直接按源文件中的webpack.server.config.js打包就可以吗

**Comment by 3Shain** [comment]
> 重新打包直接按源文件中的webpack.server.config.js打包就可以吗
> 
> > > > > 直接在wordFilter数组里面添加关键字好像不行啊
> > > > > `this.wordFilter = [ 'kimo', '风暴', '弹幕姬', '弹幕机', '别刷', '不要刷', '小鬼', 'biss', '嘴臭', '骂我', '梗', '傻逼', '弱智', '脑残', '屏蔽', 'cnm', '警察', '加群', '群号', 'QQ群', '出警', '人工智能', '老婆', 'test' ];`
> > > > 
> > > > 
> > > > 这是筛除列表，包含关键字的会直接滤掉
> > > 
> > > 
> > > 直接在server.js文件中更改可以吗？
> > > 还是说得在源文件中更改以后重新打包？
> > 
> > 
> > 理论上可以直接改，但建议重新打包。
> 
> 直接按源文件中的webpack.server.config.js打包就可以吗

ng build --prod 生成纯html bundle
或者 npm run build:ssr 生成本地部署版(包含api的服务端渲染版)

**Comment by Dreammer12138** [comment]
请问为什么每次启动都会提示`直播间信息获取失败，尝试rawId`，
而且用户头像加载不出来`GET https://bilichat.3shain.com/api/avatar/34496749 403 (Forbidden)`
还有报错`Access to XMLHttpRequest at 'https://bilichat.3shain.com/api/stat/21130785' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Dreammer12138** [comment]
请问为什么每次启动都会提示`直播间信息获取失败，尝试rawId`，
而且用户头像加载不出来`GET https://bilichat.3shain.com/api/avatar/34496749 403 (Forbidden)`
还有报错`Access to XMLHttpRequest at 'https://bilichat.3shain.com/api/stat/21130785' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

> > 重新打包直接按源文件中的webpack.server.config.js打包就可以吗
> > > > > > 直接在wordFilter数组里面添加关键字好像不行啊
> > > > > > `this.wordFilter = [ 'kimo', '风暴', '弹幕姬', '弹幕机', '别刷', '不要刷', '小鬼', 'biss', '嘴臭', '骂我', '梗', '傻逼', '弱智', '脑残', '屏蔽', 'cnm', '警察', '加群', '群号', 'QQ群', '出警', '人工智能', '老婆', 'test' ];`
> > > > > 
> > > > > 
> > > > > 这是筛除列表，包含关键字的会直接滤掉
> > > > 
> > > > 
> > > > 直接在server.js文件中更改可以吗？
> > > > 还是说得在源文件中更改以后重新打包？
> > > 
> > > 
> > > 理论上可以直接改，但建议重新打包。
> > 
> > 
> > 直接按源文件中的webpack.server.config.js打包就可以吗
> 
> ng build --prod 生成纯html bundle
> 或者 npm run build:ssr 生成本地部署版(包含api的服务端渲染版)

请问为什么每次启动都会提示`直播间信息获取失败，尝试rawId`，
而且用户头像加载不出来`GET https://bilichat.3shain.com/api/avatar/34496749 403 (Forbidden)`
还有报错`Access to XMLHttpRequest at 'https://bilichat.3shain.com/api/stat/21130785' from origin 'http://localhost:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by 3Shain** [comment]
不要直接使用bilichat.3shain.com提供的api，因为做了跨域检查。
本地部署版已经提供了简单实现。

**Comment by Dreammer12138** [comment]
> 不要直接使用bilichat.3shain.com提供的api，因为做了跨域检查。
> 本地部署版已经提供了简单实现。

我现在在源代码中改了一些地方，重新打包时发现bilichat.js没有被包进去

**Comment by 3Shain** [comment]
> > 不要直接使用bilichat.3shain.com提供的api，因为做了跨域检查。
> > 本地部署版已经提供了简单实现。
> 
> 我现在在源代码中改了一些地方，重新打包时发现bilichat.js没有被包进去

本地部署版并不需要这个文件，相应的代码已经在server.ts里。

**Comment by Dreammer12138** [comment]
谢谢大佬。我弄懂了，万分感谢
