### ISSUE TITLE
Hello-修改及功能升级意见

### ISSUE THREAD

**Issue by WTFTWTM** [3Shain/BiliChat#14]
现在已有完善的弹幕及礼物信息接收功能，请问能否实现TwiTch中的礼物及订阅展示，开放两个端口，其中一个为弹幕展示，另一个为礼物及订阅特效展示，订阅特效及礼物可使用GIF或HTML5模板来进行更换或定义。详细可以邮件交流：postmaster@alisrver.net

**Comment by 3Shain** [comment]
这个功能的需求不是特别大，可以参考alpha&chat-renderer组件自己实现。核心是使用biliws.service监听GiftMessage,然后就可以显示礼物特效之类的。
