### ISSUE TITLE
groupSimilar可能存在误伤

### ISSUE THREAD

**Issue by simon300000** [3Shain/BiliChat#22]
现在的groupSimilar用`indexOf`，只要包含之前发过的弹幕就算是Similar，这样似乎会误伤不少弹幕。
比如一个人发了`草`
另一个人之后发了`一大堆东西 草`
那么后面那个弹幕就会算作前面那个弹幕的重复

如图：可以看到`测试 233`hit了7次
<img width="232" alt="屏幕快照 2019-05-04 上午3 40 36" src="https://user-images.githubusercontent.com/12656264/57161886-414b3480-6e1f-11e9-87f1-d3f673018f25.png">
<img width="310" alt="屏幕快照 2019-05-04 上午3 40 48" src="https://user-images.githubusercontent.com/12656264/57161888-41e3cb00-6e1f-11e9-8e66-c8df11a5157e.png">

实际可能发生的情况：
<img width="253" alt="屏幕快照 2019-05-04 上午3 26 56" src="https://user-images.githubusercontent.com/12656264/57161908-4f00ba00-6e1f-11e9-9353-5098c20d6b75.png">
<img width="312" alt="屏幕快照 2019-05-04 上午3 27 05" src="https://user-images.githubusercontent.com/12656264/57161909-4f00ba00-6e1f-11e9-9d13-8322879555c2.png">

**Comment by 3Shain** [comment]
暂时添加一个长度判断，当两条长度相差一倍以上不计为相似弹幕。

**Comment by simon300000** [comment]
嘿嘿好办法 谢谢修复
