### ISSUE TITLE
【项目不相关】

### ISSUE THREAD

**Issue by 3Shain** [3Shain/BiliChat#23]
但我真的没钱了

**Comment by Afanyiyu** [comment]
1.要不是我也没钱我就
2.Contribute了就相当于交钱了，嗯
3.我还刚想问直接把BiliChat强制下放到本地部署不就省了维护server的钱了吗
4.去向Homolive要工资啊

**Comment by simon300000** [comment]
惊了，要不要部署到我的服务器上？

**Comment by Afanyiyu** [comment]
@simon300000
欸有点道理欸，多找几个小（shi）伙（you）伴（lao），然后多坑几个作为备用服务器，主服务器收到请求后随机转（把锅推）到其他服务器上
甩 锅 大 王
说到底这东西本身就是个人本地部署个人的最好啊~

**Comment by simon300000** [comment]
@Afanyiyu 具体我也不知道 @3Shain 到底缺什么了，不知道是服务器流量不足，还是单IP所以api请求过多导致会被bilibili封禁，还是没钱续费
不同问题有不同解决办法，
第一个问题我一个月3TB可以做static cdn分担点，或者用github pages，
第二个问题我也没啥好办法。。。可以考虑代理，就是速度慢。（或者直接把B站服务器上所有face url都爬下来，大概10几G吧
第三个问题 emmmmm 直接部署到我服务器上？
