### ISSUE TITLE
莫名其妙多了很多访问记录，你们有什么头猪吗

### ISSUE THREAD

**Issue by 3Shain** [3Shain/BiliChat#27]
看服务器日志上时间较为规律似乎是被爬虫了
而且都是vtuber的房间
不会是被拿来爬弹幕记录了吧？我寻思这方法效率也挺低的啊
这已经属于严重滥用行为了，但似乎用了IP代理池我还没有有效的办法阻止

@simon300000 
@Afanyiyu

**Comment by simon300000** [comment]
我的错我的错
我把你网站ifram进vtbs.moe了

**Comment by simon300000** [comment]
刚刚来这里逛来逛去想通知你来着。。。。。。

**Comment by 3Shain** [comment]
> 我的错我的错
> 我把你网站ifram进vtbs.moe了

好吧，你可以自己搭一个（所有需要的东西我都开源了），因为我这边还有日志

**Comment by simon300000** [comment]
我自己搭罢→_→！先去掉了

**Comment by 3Shain** [comment]
> 我自己搭罢→_→！先去掉了

墙裂推荐jenkins自动构建，甚至如果你想用Dockerfile也提供了

**Comment by simon300000** [comment]
不过我看现在face还没有lru-cache
不考虑加上一个吗？24小时那种

**Comment by simon300000** [comment]
ps 弹幕记录的话，我有一个repo专门拿来爬，有人想用的话可以直接拿去用
http://github.com/bilibili-dd-center/bilibili-Vtuber-danmaku/

**Comment by 3Shain** [comment]
> 不过我看现在 face url 似乎还没有 lru-cache 之类的手段
> 不考虑加上一个吗？24小时那种

有空加一个

**Comment by simon300000** [comment]
> > 不过我看现在 face url 似乎还没有 lru-cache 之类的手段
> > 不考虑加上一个吗？24小时那种
> 
> 有空加一个

你有那个BackEnd倒是不需要，主要是真有人想我这样的话可能会需要

我现在在想能不能加一个设置直接把后台给阉割掉，因为就我网页的需求，是不需要后台的

**Comment by 3Shain** [comment]
> > > 不过我看现在 face url 似乎还没有 lru-cache 之类的手段
> > > 不考虑加上一个吗？24小时那种
> > 
> > 
> > 有空加一个
> 
> 你有那个BackEnd倒是不需要，主要是真有人想我这样的话可能会需要
> 
> 我现在在想能不能加一个设置直接把后台给阉割掉，因为就我网页的需求，是不需要后台的

用nginx反向代理，添加规则 /api开头的转到后端去
数据库需要提前迁移 如果嫌麻烦你可以直接把访问数据库的代码注释掉

**Comment by simon300000** [comment]
> > > > 不过我看现在 face url 似乎还没有 lru-cache 之类的手段
> > > > 不考虑加上一个吗？24小时那种
> > > 
> > > 
> > > 有空加一个
> > 
> > 
> > 你有那个BackEnd倒是不需要，主要是真有人想我这样的话可能会需要
> > 我现在在想能不能加一个设置直接把后台给阉割掉，因为就我网页的需求，是不需要后台的
> 
> 用nginx反向代理，添加规则 /api开头的转到后端去
> 数据库需要提前迁移 如果嫌麻烦你可以直接把访问数据库的代码注释掉

不我完全不需要api什么的
因为我有roomid，而且不是shortid
也不要face→_→

**Comment by Afanyiyu** [comment]
1.惊了你们在issue版聊天我刚刚都没看见
2.楼上都是大佬说的话我一个字也看不懂
3.专门爬弹幕的repo可还行
4.我没有猪

**Comment by simon300000** [comment]
> 1.惊了你们在issue版聊天我刚刚都没看见
> 2.楼上都是大佬说的话我一个字也看不懂
> 3.专门爬弹幕的repo可还行
> 4.我没有猪

1. issue聊天流
2. 我不是dalao→_→ 我不会ts
   1. 我写了一个网站 vtbs.moe 今日某种意义上达到了DDOS BiliChat的效果
3. 嘿嘿嘿厉害吧2333
4. 放心我有
