### ISSUE TITLE
【新功能提议|REQUEST NEW FEATURE】集中讨论版

### ISSUE THREAD

**Issue by Afanyiyu** [3Shain/BiliChat#30]
🙃所有看到这的朋友们，麻烦你们给@3Shain打钱！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

打了钱之后，这里是bilichat讨论交流群的群号。如果有使用方面的问题可以进群提问，确定有issue或者enhancement的时候请使用issues或pr。
bilichat交流群：906600901

**Comment by Afanyiyu** [comment]
另外一直在issue聊天我寻思也不太好啊，要不来个“bilichat产品交流群”什么的？

**Comment by 3Shain** [comment]
有点超纲了，包括发表情包这个功能我也觉得有点超纲了。
最初的目的只是为了适配仿真油管评论栏，现在，将来也是。

但设置了alpha这个路由的目的是为了以后还能有个beta,delta...版，也许是不局限于模仿油管的版本，或是为实现特定功能的版本。不过做不做还是看有没有需求吧。目前看来，这些需求并不是很大。

所以目前的主分支大方向是稳定性+模块化重构(提升扩展性)，新功能我要往后推一点。

另外看下我提交的i18n分支，还是说我一口气做完好了

群后面找时间开一个

**Comment by simon300000** [comment]
有时间怎么搞一搞，看看能不能用vue写angular组件
（邪恶的计划出现了

**Comment by Afanyiyu** [comment]
邪恶的计划出现了
不过我估计GitHub上面已经有人在做了只不过没有造成影响
《兼收并蓄求发展——论angular与vue的互操作》
嗯嗯

**Comment by simon300000** [comment]
我大概又个办法，不过需要用webpack用loader吧
webpack好麻烦2333算了吧
不过这个cli我用不了，暂时不知道是不是我的问题

**Comment by Afanyiyu** [comment]
草 大佬出现了
话说回来我明天还有考试我现在却在作死
嗯，其实我天天都在死
undead 我 undead

**Comment by simon300000** [comment]
我不是dalao 我不是dalao
不过真巧，我明天也有考试
我现在犯了看谁有考试都是IBDP的病

**Comment by Afanyiyu** [comment]
😶
……欸不行我要睡去了
早睡早起身体好
晚安啦啦

**Comment by Afanyiyu** [comment]
🙃所有看到这的朋友们，麻烦你们给@3Shain打钱！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by simon300000** [comment]
@3Shain 
BiliChat要不要考虑弄一个代码规范？
哪里有空格，哪里换行，那样的→_→

**Comment by 3Shain** [comment]
> @3Shain
> BiliChat要不要考虑弄一个代码规范？
> 哪里有空格，哪里换行，那样的→_→

一切以angular规范为准，ng lint指令会检查代码规范性并尝试自动修正
但别随便玩那个，我会隔段时间在master分支检查

**Comment by simon300000** [comment]
> > @3Shain
> > BiliChat要不要考虑弄一个代码规范？
> > 哪里有空格，哪里换行，那样的→_→
> 
> 一切以angular规范为准，ng lint指令会检查代码规范性并尝试自动修正
> 但别随便玩那个，我会隔段时间在master分支检查

这不是会造成许多本质无建设性的commit/add/del吗（有时很迷惑

ps: https://github.com/illacceptanything/illacceptanything 潜 入 成 功

**Comment by Afanyiyu** [comment]
哇，都是做大的PR的人啊
代码规范这个一般不用自己搞吧大概（？）
不过建议每次commit或者PR之前先拿formatter检查一遍自己修改过的部分，省去单独commit的麻烦
话说回来你们有去评论区索要->打钱或者是招募翻译的吗
如果招到了日语翻译并且想要省事的话可以直接让翻译给我发邮件，我拿到字符串之后PR，这就省了“翻译步骤：第一步，注册GitHub”之类的麻烦
不过也有可能是我麻烦了♂

**Comment by simon300000** [comment]
> 哇，都是做大的PR的人啊
> 代码规范这个一般不用自己搞吧大概（？）
> 不过建议每次commit或者PR之前先拿formatter检查一遍自己修改过的部分，省去单独commit的麻烦
> 话说回来你们有去评论区索要->打钱或者是招募翻译的吗
> 如果招到了日语翻译并且想要省事的话可以直接让翻译给我发邮件，我拿到字符串之后PR，这就省了“翻译步骤：第一步，注册GitHub”之类的麻烦
> 不过也有可能是我麻烦了♂

我一般都是一边写一边检查的，不过不同人有不一样的处理方法
楼上所说，这个repo应该是按照Angular规范间断性检查，由3Shain来做，所以我们倒是不用担心太多了了。

**Comment by Afanyiyu** [comment]
嗯嗯

**Comment by Afanyiyu** [comment]
哈哈哈不行了，刚看到一位站友发了如下一句话：

quote
刚搭了个弹幕服务器，大家帮我测试下
bilichat正在运行于127.0.0.1
就这个，帮个忙，谢谢了

**Comment by simon300000** [comment]
> Afanyiyu

告诉他一下127.0.0.1是本地的意思呗
话说在哪？我要去围观下谁那么有热心→_→

**Comment by 3Shain** [comment]
为庆祝项目100star达成，抽一个contributor给我打钱，那么是谁这么幸运呢

**Comment by simon300000** [comment]
就@3Shain 吧
他贡献最多了

**Comment by Afanyiyu** [comment]
1.楼上都是逻辑奇才
2.star已经101了
3.也就是说这个项目已经被M$看上了，去喂自家IntelliCode了，恭喜恭喜
4.今晚我可能会有PR（啊现在做PR感觉就像投ボカロ稿一样，好激动www）

**Comment by Afanyiyu** [comment]
> > Afanyiyu
> 
> 告诉他一下127.0.0.1是本地的意思呗
> 话说在哪？我要去围观下谁那么有热心→_→

……要不你去告，我已经笑死了
好像是在3Shain投的专栏那里

**Comment by simon300000** [comment]
> 1.楼上都是逻辑奇才
> 2.star已经101了
> 3.也就是说这个项目已经被M$看上了，去喂自家IntelliCode了，恭喜恭喜
> 4.今晚我可能会有PR（啊现在做PR感觉就像投ボカロ稿一样，好激动www）

惊了，虽然我现在大概是vscode atom双修程序员，但是这个IntelliCode该怎么用啊→_→？（刚刚装上
（顺便vscode有没有什么好看的Theme，求推荐
<img width="1680" alt="屏幕快照 2019-05-18 下午11 19 30" src="https://user-images.githubusercontent.com/12656264/57971669-8779c980-79c3-11e9-983a-ff8917b1b62c.png">

**Comment by simon300000** [comment]
> > > Afanyiyu
> > 
> > 
> > 告诉他一下127.0.0.1是本地的意思呗
> > 话说在哪？我要去围观下谁那么有热心→_→
> 
> ……要不你去告，我已经笑死了
> 好像是在3Shain投的专栏那里

惊了，还能写专栏
我要不要给vtbs.moe也写一个2333

**Comment by Afanyiyu** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/20179549/57971735-64034e80-79c4-11e9-83ef-657f7ec303d4.png)

不说话，我已经爱死MaterialDesign了

**Comment by Afanyiyu** [comment]
> > > > Afanyiyu
> > > 
> > > 
> > > 告诉他一下127.0.0.1是本地的意思呗
> > > 话说在哪？我要去围观下谁那么有热心→_→
> > 
> > 
> > ……要不你去告，我已经笑死了
> > 好像是在3Shain投的专栏那里
> 
> 惊了，还能写专栏
> 我要不要给vtbs.moe也写一个2333

我觉得挺好

**Comment by Afanyiyu** [comment]
顺便有时间的话咱们几个尝试一下Live Share，组团开黑撸代码

**Comment by simon300000** [comment]
> 顺便有时间的话咱们几个尝试一下Live Share，组团开黑撸代码

这是个好主意！
不过我们首先要确定一下写啥2333

**Comment by Afanyiyu** [comment]
> > 顺便有时间的话咱们几个尝试一下Live Share，组团开黑撸代码
> 
> 这是个好主意！
> 不过我们首先要确定一下写啥2333

哈哈

**Comment by Afanyiyu** [comment]
PS：IntelliCode是完全智能的，智能到你都不知道它干了些什么你的工作效率就成倍的提升了
因为「它知道你接下来要写什么」

**Comment by 3Shain** [comment]
我的另一个项目 open-gf 了解下。
非常危险的项目，欢迎贡献，到时候有局子一起蹲

**Comment by simon300000** [comment]
> 我的另一个项目 open-gf 了解下。
> 非常危险的项目，欢迎贡献，到时候有局子一起蹲

哪里呀，找不着

**Comment by 3Shain** [comment]
> > 我的另一个项目 open-gf 了解下。
> > 非常危险的项目，欢迎贡献，到时候有局子一起蹲
> 
> 哪里呀，找不着

搜用户

**Comment by simon300000** [comment]
e5 b0 91 e5 a5 b3 e5 89 8d e7 ba bf e7 a7 81 e6 9c 8d ef bc 9f？

**Comment by 3Shain** [comment]
> > > > 我的另一个项目 open-gf 了解下。
> > > > 非常危险的项目，欢迎贡献，到时候有局子一起蹲
> > > 
> > > 
> > > 哪里呀，找不着
> > 
> > 
> > 搜用户
> 
> `Buffer([0xe5,0xb0,0x91,0xe5,0xa5,0xb3,0xe5,0x89,0x8d,0xe7,0xba,0xbf,0xe7,0xa7,0x81,0xe6,0x9c,0x8d,0xef,0xbc,0x9f]).toString()`

sodayo
实际意义不大，我用来练手的
有那么点技术含量也不敢拿上台面（

**Comment by simon300000** [comment]
> > > > > 我的另一个项目 open-gf 了解下。
> > > > > 非常危险的项目，欢迎贡献，到时候有局子一起蹲
> > > > 
> > > > 
> > > > 哪里呀，找不着
> > > 
> > > 
> > > 搜用户
> > 
> > 
> > `Buffer([0xe5,0xb0,0x91,0xe5,0xa5,0xb3,0xe5,0x89,0x8d,0xe7,0xba,0xbf,0xe7,0xa7,0x81,0xe6,0x9c,0x8d,0xef,0xbc,0x9f]).toString()`
> 
> sodayo
> 实际意义不大，我用来练手的
> 有那么点技术含量也不敢拿上台面（

我只会js的说，倒是帮不上忙→_→

**Comment by Afanyiyu** [comment]
局子吗，我就不去了，还有作业要写，你们先去吧😊
话说GitHub上怎么做到无痕commit的，牛逼啊

**Comment by simon300000** [comment]
`GIT_AUTHOR_NAME="Recorder" GIT_AUTHOR_EMAIL="example@example.com" GIT_COMMITTER_NAME="Recorder" GIT_COMMITTER_EMAIL="example@example.com" git -c commit.gpgsign=false commit -m "update"`
（滑稽

**Comment by simon300000** [comment]
@3Shain @Afanyiyu 快看我专栏写完啦hiahiahia
https://www.bilibili.com/read/cv2711432

**Comment by Afanyiyu** [comment]
卧槽我才想起来明天八点是第八场考试！！！
………我要不要睡了啊
听匹老板的术听到四点，我没救了

**Comment by simon300000** [comment]
> 卧槽我才想起来明天八点是第八场考试！！！
> ………我要不要睡了啊
> 听匹老板的术听到四点，我没救了

睡前点赞投币有助于考试→_→！

**Comment by Afanyiyu** [comment]
1.米娜最近都潜水啊
2.华 为 惊 现 神 操 作
3.   ide.coder.com
最近我震惊的是这个网站竟然直接还可以开终端用bash（npm集成）直接撸angular，debugger都支持
我去年的预言成真了
不过今 年 下 半 年vsonline也就出来了
到时候vsonline+live share（slack加成）+intellicode
网 吧 编 程 不 是 梦
4.另外夏色吹雪在超会议上的熟肉有人反映弹幕挡）了，有没有什么可以调整透明度或者礼物banner大小的query（讲真那个banner太长了，可以考虑左对齐，毕竟obs的浏览器捕获傻傻不能直接调大小） 这是个新功能req
5.simon要想提高你站流量可以试试做几期可视化，试试自动爬数据自动arender渲染出视频来（算了麻烦了，不过这么好的网站不可视化可惜了）
6.🤔好像没什么其他要说的了，听我的术去了

**Comment by simon300000** [comment]
可视化可以去借用见齐的代码233
不过我看目前这点数据也没啥好可视化的

**Comment by daofeng2015** [comment]
能不能显示用户等级啊.我还没搞明白那个等级是图片还是ws里面的东西

**Comment by 3Shain** [comment]
> 能不能显示用户等级啊.我还没搞明白那个等级是图片还是ws里面的东西

ws里会包含等级。目前不考虑显示用户等级。

**Comment by simon300000** [comment]
关于等级之类的，有可能可以考虑给一个不显示的元素？可以让使用者自己css调什么的

**Comment by Afanyiyu** [comment]
https://github.com/Afanyiyu/BiliChat-User-Guide

兢 兢 业 业（划去）闲来无事写文档

**Comment by 3Shain** [comment]
> 关于等级之类的，有可能可以考虑给一个不显示的元素？可以让使用者自己css调什么的
> […](#)
> 在 2019年5月25日，下午10:49，3Shain ***@***.***> 写道： 能不能显示用户等级啊.我还没搞明白那个等级是图片还是ws里面的东西 ws里会包含等级。目前不考虑显示用户等级。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

不准备提供，按照目前的目的，这不是我需要实现的功能。

**Comment by Afanyiyu** [comment]
太草了，一直到6月6号？我还从没见过大公司间断运营最主要的功能的…
…这tm绝壁要大改…接口规则都改了…
…问题我寻思这有什么好改的啊？还特意弄六个变量，弹幕类型这么多的吗……
话说回来现在的弹幕还有什么地方不完善的？
虽说关停弹幕不会直接影响收入来源，虽说重构有n多好处，不过大部分PM一般都会选择“shi'shan堆shi”吧…这一点倒是要给点个赞，我也挺期待有什么新功能的…
以及我觉得这六个变量肯定有几个是要留下来向后兼容的吧，这一次上线之后咋也得撑个几年？
话说回来我们也不要用startswith而是只用comtains得了。免得以后再生麻烦…我们也来做个向后兼容。吧233（溜了溜了）

**Comment by FlameRat** [comment]
是不是可以做一个手动SC？
比如缓存礼物信息20s，20s内发送的第一条弹幕会和礼物信息一起组合成油管样式的SC显示出来。

**Comment by simon300000** [comment]
我记得的确说过这个计划，似乎是和前一个弹幕一起显示来着。不过不清楚具体是什么情况。

**Comment by 3Shain** [comment]
> 是不是可以做一个手动SC？
> 比如缓存礼物信息20s，20s内发送的第一条弹幕会和礼物信息一起组合成油管样式的SC显示出来。

虽然我没说，但这功能已经实装了，取60秒内最后一条发言

**Comment by FlameRat** [comment]
> > 是不是可以做一个手动SC？
> > 比如缓存礼物信息20s，20s内发送的第一条弹幕会和礼物信息一起组合成油管样式的SC显示出来。
> 
> 虽然我没说，但这功能已经实装了，取60秒前最后一条发言

居然已经有了么ww 配置方法？想试试。(这算内测么)

**Comment by FlameRat** [comment]
还有个想法 通过正则提取之类的方法把礼物信息摘出来，然后把提示信息什么的通过本地配置的方法进行更改(换成日文英文、加梗)。
然后现在上舰似乎是跟普通礼物用的同一套样式？ 虽然可以通过设置阈值换成油管的绿色，但是不知道礼物和舰长价格用的是折前还是折后价格 也挺头疼的。

**Comment by 3Shain** [comment]
> > > 是不是可以做一个手动SC？
> > > 比如缓存礼物信息20s，20s内发送的第一条弹幕会和礼物信息一起组合成油管样式的SC显示出来。
> > 
> > 
> > 虽然我没说，但这功能已经实装了，取60秒前最后一条发言
> 
> 居然已经有了么ww 配置方法？想试试。(这算内测么)

不需要配置方法，默认已经可以上了

**Comment by 3Shain** [comment]
> 最新出了个心愿墙,能否安排下？

说实话没搞懂这个功能

**Comment by Afanyiyu** [comment]
买了块1T的硬盘，除了装MacOS还能怎么用，大家有什么头猪吗

**Comment by Afanyiyu** [comment]
https://github.com/Afanyiyu/BiliChat-User-Guide/blob/master/Deploy.md
里面已经加入了docker的部署方法，以及使用淘宝npm加速npm install的方法
同时采用了cnpm和npm双install，确保二者服务器任一出现bug都不会对docker的build造成影响
（对没错就是因为cnpm的服务器拽不下@nguniversal来（到现在也是）我才加的这个特性）
现在已经可以直接从docker hub往下pull了
commit全在我fork的repo的Docker分支，commit太多我就不PR了

你看Il·三脚猫·Harper又学了个Docker
哈哈O(∩_∩)O（旁白《=不要脸（x））

**Comment by simon300000** [comment]
> https://github.com/Afanyiyu/BiliChat-User-Guide/blob/master/Deploy.md
> 里面已经加入了docker的部署方法，以及使用淘宝npm加速npm install的方法
> 同时采用了cnpm和npm双install，确保二者服务器任一出现bug都不会对docker的build造成影响
> （对没错就是因为cnpm的服务器拽不下@nguniversal来（到现在也是）我才加的这个特性）
> 现在已经可以直接从docker hub往下pull了
> commit全在我fork的repo的Docker分支，commit太多我就不PR了
> 
> 你看Il·三脚猫·Harper又学了个Docker
> 哈哈O(∩_∩)O（旁白《=不要脸（x））

如果用npm，但是 `--registry=https://registry.npm.taobao.org` 呢？

**Comment by Afanyiyu** [comment]
@simon300000 由于淘宝npm有部分package是坏的，所以用cnpm i之后必须用npm重新i一下。第二次npm在i的时候会跳过以及i好的包。

**Comment by Afanyiyu** [comment]
如果3Shain需要的话可以自己PR哒~我就不PR了
另外这个squash只是在merge的时候有用啊……也就是说我无论如何都删不掉我的黑历史了吗……
（那酸酸乳是怎么抹掉repo的…）

另外我前两天刚刚干完人生一件大事，这两天24h待机，欢迎提req或者来live share~
顺便问下除了计算机科学还有什么专业推荐的吗
（大人说话小孩子强行插嘴（x））

**Comment by simon300000** [comment]
3Shain-高中生
Simon-高中生
其他人-不知道

大人说话（✘
小孩说话（✔

**Comment by Afanyiyu** [comment]
诶卧槽
这
卧槽震惊
诶诶诶
我还以为你们俩都是在职
这
这
那
…
那你们有什么专业推荐的吗


欸卧槽
之前看3Shain对产品功能有严格限制，一直觉得不仅是为了兼容chatboxのcss，而且是在职人员的良好习惯（抑或是hololive的PM直 接 嘱 咐）
包括他说的话都体现很多考虑
哇这个时代已经改变了吗
啊啊啊
（那我找谁问填报志愿的事）
话说你们高几

**Comment by simon300000** [comment]
@Afanyiyu 
咦
欢迎加入GitHub DD CENTER，群聊号码：663606562

**Comment by Afanyiyu** [comment]
嗯你终于想起这事了
等一下我开个电脑

**Comment by Afanyiyu** [comment]
另外我这两天有个C#的企划，挺急的，你们要来contri吗大体思路就是每隔一定时间自动把指定文件（aep，ai，psd，pptx，cpr，flp）解压到某工作目录，然后用git同步之后再打包放回去
以实现这些应用的多人协作同步
否则的话我基本没办法跟我studio的人实现编曲和视频的同步，，，
话说回来咱们几个人的slack，gitter，msteam，azure devops也可以安排一下，（尤其是devops的生产自动化特别方便还免费），大 家 都 是 朋 友

**Comment by Afanyiyu** [comment]
https://teams.microsoft.com/l/team/19%3a15f6a64aff594b7883c603260e0dd9c6%40thread.skype/conversations?groupId=116d4f79-6cbd-4d19-a702-7668cb0d4f90&tenantId=c2dc4710-e858-4ad4-b464-7dbfaaef5919

请加入此团队。嗯嗯(●'◡'●)

**Comment by baolan-zifu** [comment]
能不能兼容更多的直播平台呢？或者搞个通用的API什么的

**Comment by TianQiBuTian** [comment]
B站新出了“醒目留言”（等于SC），最低30元（30000金瓜子）无上限（无法输小数点）

**Comment by 3Shain** [comment]
> B站新出了“醒目留言”（等于SC），最低30元（30000金瓜子）无上限（无法输小数点）

已实现基本支持。

**Comment by H-N-HONOO** [comment]
> > B站新出了“醒目留言”（等于SC），最低30元（30000金瓜子）无上限（无法输小数点）
> 
> 已实现基本支持。

请问怎么设置呢？

**Comment by 3Shain** [comment]
> > > B站新出了“醒目留言”（等于SC），最低30元（30000金瓜子）无上限（无法输小数点）
> > 
> > 
> > 已实现基本支持。
> 
> 请问怎么设置呢？

使用最新版即可，无需额外设置

**Comment by Gaiyas** [comment]
想问一下能不能单独只显示主播弹幕或者房管弹幕之类的？

**Comment by lolisound** [comment]
请问能否设置弹幕停留时间？

**Comment by blackfoxsar** [comment]
有部分金瓜子礼物不能显示，不知道是礼物太新了还是怎样emm？
使用的是v1.3.2版
![image](https://user-images.githubusercontent.com/15705262/78130060-8f175500-7453-11ea-85cc-b3b036416c6d.png)

**Comment by Qixingchen** [comment]
> 有部分金瓜子礼物不能显示，不知道是礼物太新了还是怎样emm？
> 使用的是v1.3.2版
> ![image](https://user-images.githubusercontent.com/15705262/78130060-8f175500-7453-11ea-85cc-b3b036416c6d.png)

minGiftValue 最低显示礼物价值,默认20

**Comment by blackfoxsar** [comment]
> minGiftValue 最低显示礼物价值,默认20

按照 [CONFIG.md](https://github.com/3Shain/BiliChat/blob/05fbeb1cf53405542649237fd01f5287c5e09565/CONFIG.md) 的说法进行了修改，仍然不起作用。
另：我使用了systemd，系统为debian 10，在/usr/local/bin 和 /usr/local/lib/node_modules/bilichat 以及 /usr/local/lib/node_modules/bilichat/dist 三个位置均放置了同一份config.json文件。

以及个人建议config.json是不是固定到某个指定的位置更好？

**Comment by 3Shain** [comment]
> > minGiftValue 最低显示礼物价值,默认20
> 
> 按照 [CONFIG.md](https://github.com/3Shain/BiliChat/blob/05fbeb1cf53405542649237fd01f5287c5e09565/CONFIG.md) 的说法进行了修改，仍然不起作用。
> 另：我使用了systemd，系统为debian 10，在/usr/local/bin 和 /usr/local/lib/node_modules/bilichat 以及 /usr/local/lib/node_modules/bilichat/dist 三个位置均放置了同一份config.json文件。
> 以及我同时尝试了单独执行bilichat并按照说明文档，在执行的目录下放置了一份config.json，依旧不起作用。
> 
> 以及个人建议config.json是不是固定到某个指定的位置更好？

一个||判断造成的bug导致minGiftValue不能填0，填一个极小值试试
config.json读的就是进程执行相对路径，不是执行程序所在文件路径，个人认为这样最方便，但之后会加个参数指定文件位置

**Comment by blackfoxsar** [comment]
> > > minGiftValue 最低显示礼物价值,默认20
> > 
> > 
> > 按照 [CONFIG.md](https://github.com/3Shain/BiliChat/blob/05fbeb1cf53405542649237fd01f5287c5e09565/CONFIG.md) 的说法进行了修改，仍然不起作用。
> > 另：我使用了systemd，系统为debian 10，在/usr/local/bin 和 /usr/local/lib/node_modules/bilichat 以及 /usr/local/lib/node_modules/bilichat/dist 三个位置均放置了同一份config.json文件。
> > 以及我同时尝试了单独执行bilichat并按照说明文档，在执行的目录下放置了一份config.json，依旧不起作用。
> > 以及个人建议config.json是不是固定到某个指定的位置更好？
> 
> 一个||判断造成的bug导致minGiftValue不能填0，填一个极小值试试
> config.json读的就是进程执行相对路径，不是执行程序所在文件路径，个人认为这样最方便，但之后会加个参数指定文件位置

minGiftValue我感觉不能设置0 所以我都是设置的1
以及我感觉可能跟这个设置没有关系，我测试了一下送21个礼物，但依旧不会显示。
![image](https://user-images.githubusercontent.com/15705262/78224475-97c76400-7503-11ea-99af-9bd02154e52c.png)

**Comment by 3Shain** [comment]
> > > > minGiftValue 最低显示礼物价值,默认20
> > > 
> > > 
> > > 按照 [CONFIG.md](https://github.com/3Shain/BiliChat/blob/05fbeb1cf53405542649237fd01f5287c5e09565/CONFIG.md) 的说法进行了修改，仍然不起作用。
> > > 另：我使用了systemd，系统为debian 10，在/usr/local/bin 和 /usr/local/lib/node_modules/bilichat 以及 /usr/local/lib/node_modules/bilichat/dist 三个位置均放置了同一份config.json文件。
> > > 以及我同时尝试了单独执行bilichat并按照说明文档，在执行的目录下放置了一份config.json，依旧不起作用。
> > > 以及个人建议config.json是不是固定到某个指定的位置更好？
> > 
> > 
> > 一个||判断造成的bug导致minGiftValue不能填0，填一个极小值试试
> > config.json读的就是进程执行相对路径，不是执行程序所在文件路径，个人认为这样最方便，但之后会加个参数指定文件位置
> 
> minGiftValue我感觉不能设置0 所以我都是设置的1
> 以及我感觉可能跟这个设置没有关系，我测试了一下送21个礼物，但依旧不会显示。
> ![image](https://user-images.githubusercontent.com/15705262/78224475-97c76400-7503-11ea-99af-9bd02154e52c.png)
> 
> 另外我尝试直接改了main.js里面的数值为1 重启后再测试也是问题依旧
> 
> 顺便大佬您在Github上留的个人首页502了emm

控制变量测试呢，比如换个礼物，用url参数，可以配合另一个参数用银瓜子测试

首页本来也没东西（

**Comment by blackfoxsar** [comment]
> 控制变量测试呢，比如换个礼物，用url参数，可以配合另一个参数用银瓜子测试
> 
> 首页本来也没东西（

![image](https://user-images.githubusercontent.com/15705262/78228482-b6c8f480-7509-11ea-8526-533abfedb096.png)
换了一个礼物↑

![image](https://user-images.githubusercontent.com/15705262/78228552-cfd1a580-7509-11ea-8b8e-14cae1f910f2.png)
有换了一个礼物并在URL后面加了参数↑

然后金瓜子不够了Orz

![image](https://user-images.githubusercontent.com/15705262/78228720-07405200-750a-11ea-9adf-1584b1e7d884.png)
URL上加了"?minGiftValue=1&silverGiftRatio=1"后，辣条20个↑

![image](https://user-images.githubusercontent.com/15705262/78228843-29d26b00-750a-11ea-882e-d678fdeb7280.png)
URL上加了"?minGiftValue=1&silverGiftRatio=1"后，辣条1个↑

![image](https://user-images.githubusercontent.com/15705262/78228931-42428580-750a-11ea-9c1d-ccd76c9034fa.png)
URL上加了"?minGiftValue=1&silverGiftRatio=0.1"后，辣条19个↑

![image](https://user-images.githubusercontent.com/15705262/78229071-7322ba80-750a-11ea-8c06-74d310a447df.png)
URL上加了"?minGiftValue=1&silverGiftRatio=0.1"后，辣条21个↑

![image](https://user-images.githubusercontent.com/15705262/78229088-7a49c880-750a-11ea-822d-52b621063ada.png)
URL上加了"?minGiftValue=1&silverGiftRatio=0.1"后，辣条201个↑

![image](https://user-images.githubusercontent.com/15705262/78229104-7fa71300-750a-11ea-8f41-11401ee63c9a.png)
URL上加了"?minGiftValue=1&silverGiftRatio=20"后，辣条1个↑

怎么突然感觉是不是“礼物的价值”影响了这个问题……？

**Comment by 3Shain** [comment]
@blackfoxsar 吃瓜一毛钱一个，minGiftValue应该得到0.1

**Comment by blackfoxsar** [comment]
> @blackfoxsar 吃瓜一毛钱一个，minGiftValue应该得到0.1
咦，原来单位是按照1000:1来计算的吗？

**Comment by blackfoxsar** [comment]
> @blackfoxsar 吃瓜一毛钱一个，minGiftValue应该得到0.1

![image](https://user-images.githubusercontent.com/15705262/78230607-86368a00-750c-11ea-8336-67f8c269d356.png)
大概知道发生了什么了……我改了main.js后链接用错了（用成了 3shain.com 的链接了……）总之目前已经能正常显示了=w=
谢谢大佬帮忙解决问题=w=

**Comment by Tup0lev** [comment]
**新功能提议**

使用户可以屏蔽自定义关键词或者正则，或者加载类似 https://github.com/jnxyp/Bilibili-Block-List 中的xml文件，使被匹配到的弹幕不被显示

**Comment by 8MiYile** [comment]
## 贡献一条镜像站地址
https://bilichat.home.8mi.tech

**Comment by 8MiYile** [comment]
## 新功能建议,关于环境的
cPanel的NodeJS环境无法加载BiliChat,先是运行了git拉取的,再切换成Release的压缩包文件,但还是无法运行,设置了log输出地址了,但没有任何log,只在项目文件夹额外创建了两个文件夹,public与tmp

**Comment by Afanyiyu** [comment]
> ## 新功能建议,关于环境的
> cPanel的NodeJS环境无法加载BiliChat,先是运行了git拉取的,再切换成Release的压缩包文件,但还是无法运行,设置了log输出地址了,但没有任何log,只在项目文件夹额外创建了两个文件夹,public与tmp
> 个人建议,发布cPanel服务端的使用教程

非BiliChat的问题和意见不建议在此版发布。

**Comment by fenyuluoshang** [comment]
## 一条建议
大佬是否考虑更换b站新版的接口
以及提供更广泛的信息给UI制作者，比我我正在想帮朋友定制一个UI，其实很希望一个持续更新的接口项目作为依赖
## 一条看完这个项目我想做(或者说是正在做)的事
我在试图使用electron包装这个项目并为大佬提供一个小白也可以自己手动调整config的UI，如果可以，大佬可以考虑给我提供更多的接口

**Comment by Afanyiyu** [comment]
啊

1.你所说的新版接口是什么啊  源码都在这摆着了还能有什么更广泛的信息（

2.ConfigUI这个倒是已经有人做过了（隔壁）不过你想做也可以做
但是能够提供的信息没有更多了啊 源码都在那里放着了

（另外3shain最近大概很忙吧 不知道他能不能及时回复你（

**Comment by fenyuluoshang** [comment]
我试图输出了message，比如收费的那个跨播，是可以显示用户牌子等级、舰长进入直播间之类的=.=

**Comment by Afanyiyu** [comment]
哦，你是指 [这里](https://github.com/3Shain/BiliChat/blob/master/src/app/message-processor.service.ts) 没有对所有可能的 CMD 进行处理吧
这也不是 BiliChat 的接口啊，是B站官方的（

CMD 的处理在 [这里](https://github.com/EricEcho/BilibiliTool/blob/master/doc/danmu-cmd.md) 有着最为详细的参考，同时 [这里](https://github.com/xfgryujk/blivedm/blob/master/blivedm.py) 有一些可以参考的东西。

**Comment by A1exInamin** [comment]
**新功能建议**

今天研究了一下自定义配置文档，对 `customEmotions` 这个功能很喜欢，但是感觉现在的全文匹配在实际应用中会有一些缺陷，举例如下：

已有表情贴纸定义【贴贴】，但是在直播中经常出现的词组会是【XX贴贴】，这时就无法实现对部分内容匹配进行显示了。

所以想请教一下能否实现匹配弹幕的部分内容进行替换呢

**Comment by 3Shain** [comment]
> **新功能建议**
> 
> 今天研究了一下自定义配置文档，对 `customEmotions` 这个功能很喜欢，但是感觉现在的全文匹配在实际应用中会有一些缺陷，举例如下：
> 
> 已有表情贴纸定义【贴贴】，但是在直播中经常出现的词组会是【XX贴贴】，这时就无法实现对部分内容匹配进行显示了。
> 
> 所以想请教一下能否实现匹配弹幕的部分内容进行替换呢

因为图片尺寸不规范，会造成排版不美观的原因，所以没有考虑部分替换的方式。
对于类emoji的表情替换，大概会做成一个新功能（但目前而言需求还是很模糊的

**Comment by blackfoxsar** [comment]
npm版本已经非常久没更新了，建议更新一下
![image](https://user-images.githubusercontent.com/15705262/91174114-cbf12a80-e719-11ea-8cc2-83d33c925215.png)

**Comment by Afanyiyu** [comment]
目前其实是推荐使用公共服务的，最为稳定
不过确实需要更新一下 @3Shain

**Comment by blackfoxsar** [comment]
https://github.com/3Shain/BiliChat/issues/30#issuecomment-679994835
公共服务有提到过建议自己建立，外加什么压力都压在3Shain桑提供的服务上面可能也不太好www（服务器运行成本之类的）？
懂的人倒是clone一下然后可以自己搞一下，但是恐怕普通用户有点麻烦了？大概

**Comment by Afanyiyu** [comment]
氦，其实他现在已经不提倡自己部署了，因为用户自己部署的服务总会出奇奇怪怪的问题
不过npm上的包确实该更新了

**Comment by blackfoxsar** [comment]
贡献一个镜像站

https://bilichat.foxcloud.app/

PS：此版本礼物显示有改动，如不指定则默认超过1元即会显示
