### ISSUE TITLE
检测脚本+封禁用户

### ISSUE THREAD

**Issue by 3Shain** [3Shain/BiliChat#34]
前一个做不到，但后一个还是可以的（指屏蔽指定uid

@simon300000 你的弹幕记录有UID吗，昨天MIO的B限有很多脚本哥，我要去杀一波

**Comment by Afanyiyu** [comment]
……嗯……这是help wanted？
脚本草，vtb不是净土吗…
啊直播不存弹幕的哈，，，为了防范什么的是不是要搞一个近期弹幕存档/直播弹幕存档什么的？（……行车记录仪？）
好奇除了封禁还有其他什么杀法没😶

**Comment by simon300000** [comment]
对不起我的记录暂时没有用户名
不过我准备记录用户数字mid了
的确这样配合一下能有更多好处
今天去更新一波

**Comment by TomoeMami** [comment]
昨晚的弹幕我存得有，等会折腾一下传上来

**Comment by TomoeMami** [comment]
https://raw.githubusercontent.com/bilibili-dd-center/AutoCSV/master/mio0517.csv

**Comment by TomoeMami** [comment]
我再传一份我提取的脚本哥发言名单

**Comment by TomoeMami** [comment]
https://github.com/bilibili-dd-center/AutoCSV/blob/master/mio0517list.csv

**Comment by simon300000** [comment]
这种脚本会循环利用吗？一个vtb房间用完去另一个再刷
这样的话就很有屏蔽价值了

**Comment by TomoeMami** [comment]
总之先给直播官方反馈一下
![Snipaste_2019-05-18_17-55-36](https://user-images.githubusercontent.com/16950305/57967846-3ef7e700-7996-11e9-931f-affc89e9646f.png)

**Comment by Afanyiyu** [comment]
哇，楼上厉害了
