### ISSUE TITLE
能否出个服务器部署教程呢？

### ISSUE THREAD

**Issue by daofeng2015** [3Shain/BiliChat#38]

**Comment by Afanyiyu** [comment]
我倒是正在写，不过什么时候写好就不知道了

**Comment by Afanyiyu** [comment]
一会3S来了问问他吧

**Comment by 3Shain** [comment]
把本地版运行在服务器上就行了呀?

**Comment by Afanyiyu** [comment]
（小声）我在做各种没用的动图演示
build和serve时请记得使用package json里面提供的ssr模式

**Comment by 3Shain** [comment]
> （小声）我在做各种没用的动图演示
> build和serve时请记得使用package json里面提供的ssr模式

录视频效率会不会高一点

**Comment by Afanyiyu** [comment]
> > （小声）我在做各种没用的动图演示
> > build和serve时请记得使用package json里面提供的ssr模式
> 
> 录视频效率会不会高一点

不会（确信）
几秒钟就能在当前网站看完的gif录成视频少说也要看几分钟，还要打开哔哩哔哩，超麻烦
文档、md什么的中间放gif是最好的解决方案

**Comment by 3Shain** [comment]
那gif的操作还要足够简单呐，点几下鼠标的那种操作

**Comment by daofeng2015** [comment]
我试过用npm直接装的,但是前端要么没响应,要么漏弹幕.....

**Comment by Afanyiyu** [comment]
> 那gif的操作还要足够简单呐，点几下鼠标的那种操作

现在正在做安装部署到使用一条路文档啊（犭），bilichat超方便的，任何一个操作都不会超过5s呐
@daofeng2015 不npm装还要怎么装啊，最后不都是node基

**Comment by daofeng2015** [comment]
我试过用npm build过,但是网页刷新不出来

**Comment by 3Shain** [comment]
> 我试过用npm build过,但是网页刷新不出来

你build的姿势不对？我觉得你可能是指build了前端代码
编译服务端渲染
npm run build:ssr
之后运行node dist/server

或者直接从npm下载-> npm install -g bilichat，然后随处输入指令bilichat就可以了

**Comment by daofeng2015** [comment]
> > 我试过用npm build过,但是网页刷新不出来
> 
> 你build的姿势不对？我觉得你可能是指build了前端代码
> 编译服务端渲染
> npm run build:ssr
> 之后运行node dist/server
> 
> 或者直接从npm下载-> npm install -g bilichat，然后随处输入指令bilichat就可以了
