### ISSUE TITLE
能否增加本地comment转发

### ISSUE THREAD

**Issue by Xianbei233** [3Shain/BiliChat#4]
指主播本地输入转发，不再需要进直播间发送评论（不过vtb们好像不需要这个鸡肋功能（救救聋哑小主播们（（（

**Comment by 3Shain** [comment]
直接浏览器打开直播间地址不就好了嘛（（（
这个项目本质只是展示性质，obs浏览器源也做不到交互所以原理上也做不到啊（悲

**Comment by Xianbei233** [comment]
您说的对，就算主播不是盯着obs浏览器源的效果而开着浏览器在源页面那进行弹幕浏览，在源页面加comment栏做转发功能也是麻烦又鸡肋，我知道错了，下次再也不敢了（（（

**Comment by 3Shain** [comment]
> 您说的对，就算主播不是盯着obs浏览器源的效果而开着浏览器在源页面那进行弹幕浏览，在源页面加comment栏做转发功能也是麻烦又鸡肋，我知道错了，下次再也不敢了（（（

主要是，这个没有用户验证功能，开这个的不一定就一定是房主，要是被冒充发言就不好了。
不过确实有打算为主播另做一个用于统计/查看评论的页面，因为b站本来那个也是花花绿绿的还滑得莫名的快，然后我还打算加入统计内容，比如词频啊平均速度啊礼物数量价值啊之类的
