### ISSUE TITLE
使用docker构建镜像出错

### ISSUE THREAD

**Issue by daofeng2015** [3Shain/BiliChat#43]
![20190602133514](https://user-images.githubusercontent.com/14891398/58757253-b18ec800-853b-11e9-8923-305c7ea0ce65.jpg)
执行的是docker build -t bilichat:v1 /root/BiliChat这个命令

**Comment by 3Shain** [comment]
从图中信息判断,似乎是因为编译机器内存不足导致的。

公共服务器使用相同的Dockerfile进行持续部署未出现任何问题。

**Comment by Afanyiyu** [comment]
（都 是 夜 猫 子）

**Comment by 3Shain** [comment]
> （都 是 夜 猫 子）

其实可以更早回复的，但是新开issue没给我邮件提醒，所以没得到及时处理，我去查下有没有这个功能

**Comment by daofeng2015** [comment]
> 从图中信息判断,似乎是因为编译机器内存不足导致的。
> 
> 公共服务器使用相同的Dockerfile进行持续部署未出现任何问题。

内存不足啊....好吧.可能我这服务器太低了
