### ISSUE TITLE
[Feature/Bug]当指定wordFilter参数时无法解除默认的关键词屏蔽

### ISSUE THREAD

**Issue by sandtechnology** [3Shain/BiliChat#61]
请问"自行修改"指的是需要修改代码实现解除吗？
如果是，那能否加入当指定wordFilter参数为空时移除默认关键词屏蔽的功能呢？
因为有的时候关键词会误伤，比如如下弹幕：
>这个梗是老生常谈了（触发关键词“梗”）
>别刷新，阿B炸了（触发关键词“别刷”）
>感谢主播送出的问号风暴（触发关键词“风暴”）

这样会造成反馈不佳的误解，能否解除或者采用更好的机制呢？

**Comment by sandtechnology** [comment]
Update：刚刚翻到了相关解析的代码，原来是累计的
https://github.com/3Shain/BiliChat/blob/be6daa85bb7dcbaa8c47beb00e2e83c2207d13e3/src/app/gkd/gkd.component.ts#L60
如果懒的话我应该可以直接PR（

**Comment by 3Shain** [comment]
> Update：刚刚翻到了相关解析的代码，原来是累计的
> https://github.com/3Shain/BiliChat/blob/be6daa85bb7dcbaa8c47beb00e2e83c2207d13e3/src/app/gkd/gkd.component.ts#L60
> 
> 
> 如果懒的话我应该可以直接PR（

请（（（
