### ISSUE TITLE
i18n多语言

### ISSUE THREAD

**Issue by 3Shain** [3Shain/BiliChat#8]
随着工具的推广，多语言功能也显得必要了。

**Comment by Afanyiyu** [comment]
#24
//Il-Harper:
//这TS太TM难弄了，我C#做一个带GUI的计算器也只需要5分钟好吧……
//明天我再继续做……
//今天晚上用了一个小时现学现卖的TS……还好我有过(guo)硬(qi)的C#基础……
PS:测试通过了放心
第一次用PR，请多指教

**Comment by Afanyiyu** [comment]
@Aperture-Electronic

您好，我从<https://github.com/closebilibili/DMCA-takedown/pull/12>了解到您对日语较为熟悉，这个BiliChat项目是BiliBili上许多人都在使用的直播弹幕系统，希望您能帮助改进<https://github.com/3Shain/BiliChat/blob/master/src/assets/i18n/ja.json>的翻译。谢谢。

Translate by Google

Hello, I learned from <https://github.com/closebilibili/DMCA-takedown/pull/12> that you are familiar with Japanese. This BiliChat project is a live barrage system used by many people on BiliBili. Hope You can help improve the translation of <https://github.com/3Shain/BiliChat/blob/master/src/assets/i18n/ja.json>. Thank you.

こんにちは、私はあなたが日本語に精通していることを<https://github.com/closebilibili/DMCA-takedown/pull/12>から学びましたこのBiliChatプロジェクトはBiliBiliの上で多くの人々によって使用される生の連発システムです。 あなたは<https://github.com/3Shain/BiliChat/blob/master/src/assets/i18n/ja.json>の翻訳を改善するのを助けることができます。 ありがとうございます。
